In [2]:
list1 = [5,8,9,15,35,52,26,4,20]

In [4]:
mean_list1 = sum(list1) / len(list1)
mean_list1

19.333333333333332

In [ ]:
def mean(input_list):
    mean = sum(input_list) / len(input_list)
    return mean

In [9]:
mean(list1)

19.333333333333332

In [7]:
sum(list1)

174

In [23]:
def median (input_list):
    sorted_list = sorted(input_list)
    length = len(input_list)
    if length % 2 ==0:
        first_position = input_list[length//2]
        second_position = input_list[length//2-1]
        median = (first_position + second_position) /2
    else:
        median = input_list[length//2]
    return median

In [24]:
median(list1)

15

In [16]:
def stdev(input_list):
    squared_list = []
    n = len(input_list)
    mean = sum(input_list) / n
    for i in input_list:
        squared_list.append((i-mean)**2)
    sq_sum = sum(squared_list)
    variance = sq_sum / n
    stdev = variance ** (1/2)
    return stdev

In [18]:
stdev(list1)

15.0996688705415

In [26]:
for i in range(len(list1)):
    print(stdev(list1[i:]))

15.0996688705415
14.947825928876748
14.568627181693671
14.158821357098274
13.032267646115928
12.07010770457331
10.780641085864152
8.5
0.0


In [27]:
def descriptive_statistics(input_list):
    input_list.sort()
    length = len(input_list)
    if length % 2 == 0: # for even number of numbers
        # first position
        first_position = input_list[length//2]
        second_position = input_list[length//2-1]
        median = (first_position + second_position) / 2
    else: # for odd number of numbers
        median = input_list[length//2]
    
    mean = sum(input_list) / len(input_list)
    
    squared_list = []
    n = len(input_list)
    mean = sum(input_list) / n
    for i in input_list:
        squared_list.append((i-mean)**2)
    sq_sum = sum(squared_list)
    variance = sq_sum / n
    stdev = variance ** (1/2)

    print("Min: ", min(input_list))
    print("Max: ", max(input_list))
    print("Mean: ", mean)
    print("Median: ", median)
    print("Variance: ", variance)
    print("StDev: ", stdev)

In [28]:
descriptive_statistics(list1)

Min:  4
Max:  52
Mean:  19.333333333333332
Median:  15
Variance:  228.0
StDev:  15.0996688705415


In [29]:
pip install numpy

     --------------------------------------- 15.1/15.1 MB 22.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Masayo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [30]:
import numpy as np

In [31]:
array_1d = np.array(list1)

In [32]:
array_1d.min()

4

In [33]:
array_1d.mean()

19.333333333333332

In [34]:
array_1d.max()

52

In [35]:
array_1d.std()

15.0996688705415

In [36]:
array_2d = np.array([list1,list1])

In [37]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 26, 35, 52]])

In [38]:
array_2d.ndim

2

In [39]:
array_1d.ndim

1

In [40]:
array_5d = np.array([1,2,5,6,8], ndmin=5)

In [41]:
array_5d

array([[[[[1, 2, 5, 6, 8]]]]])

In [42]:
array_3d = np.array([1,2,5,6,8], ndmin=3)

In [43]:
array_3d

array([[[1, 2, 5, 6, 8]]])

In [44]:
array_2d[0]

array([ 4,  5,  8,  9, 15, 20, 26, 35, 52])

In [45]:
array_2d[0,-3]

26

In [47]:
array_3d = np.array([[list1, list1], [list1,list1]])

In [48]:
array_3d

array([[[ 4,  5,  8,  9, 15, 20, 26, 35, 52],
        [ 4,  5,  8,  9, 15, 20, 26, 35, 52]],

       [[ 4,  5,  8,  9, 15, 20, 26, 35, 52],
        [ 4,  5,  8,  9, 15, 20, 26, 35, 52]]])

In [50]:
array_2d[0,2::2]

array([ 8, 15, 26, 52])

In [51]:
array_2d.shape

(2, 9)

In [52]:
array_1d.shape

(9,)

In [53]:
array_2d.reshape(5,4)

ValueError: cannot reshape array of size 18 into shape (5,4)

In [54]:
array_2d(5,-1)

TypeError: 'numpy.ndarray' object is not callable

In [56]:
array_2d.flatten()

array([ 4,  5,  8,  9, 15, 20, 26, 35, 52,  4,  5,  8,  9, 15, 20, 26, 35,
       52])

In [57]:
array_2d.ravel()

array([ 4,  5,  8,  9, 15, 20, 26, 35, 52,  4,  5,  8,  9, 15, 20, 26, 35,
       52])

In [58]:
for i in array_3d:
    print(i)

[[ 4  5  8  9 15 20 26 35 52]
 [ 4  5  8  9 15 20 26 35 52]]
[[ 4  5  8  9 15 20 26 35 52]
 [ 4  5  8  9 15 20 26 35 52]]


In [60]:
for i in array_3d:
    for a in i:
        print(a)

[ 4  5  8  9 15 20 26 35 52]
[ 4  5  8  9 15 20 26 35 52]
[ 4  5  8  9 15 20 26 35 52]
[ 4  5  8  9 15 20 26 35 52]


In [61]:
for i in array_3d:
    for a in i:
        print(a)

[ 4  5  8  9 15 20 26 35 52]
[ 4  5  8  9 15 20 26 35 52]
[ 4  5  8  9 15 20 26 35 52]
[ 4  5  8  9 15 20 26 35 52]


In [62]:
array_3d

array([[[ 4,  5,  8,  9, 15, 20, 26, 35, 52],
        [ 4,  5,  8,  9, 15, 20, 26, 35, 52]],

       [[ 4,  5,  8,  9, 15, 20, 26, 35, 52],
        [ 4,  5,  8,  9, 15, 20, 26, 35, 52]]])

In [63]:
for i in array_2d:
    for a in i:
        for b in a:
            print(b)

TypeError: 'numpy.int32' object is not iterable

In [64]:
for i in np.nditer(array_3d):
    print(i)

4
5
8
9
15
20
26
35
52
4
5
8
9
15
20
26
35
52
4
5
8
9
15
20
26
35
52
4
5
8
9
15
20
26
35
52


In [65]:
# NumPy also has an enumerate() function

for a,b in np.ndenumerate(array_2d):
    print(a,b)

(0, 0) 4
(0, 1) 5
(0, 2) 8
(0, 3) 9
(0, 4) 15
(0, 5) 20
(0, 6) 26
(0, 7) 35
(0, 8) 52
(1, 0) 4
(1, 1) 5
(1, 2) 8
(1, 3) 9
(1, 4) 15
(1, 5) 20
(1, 6) 26
(1, 7) 35
(1, 8) 52


In [66]:
array1 = [1,2,3,4]
array2 = [5,6,7,8]

In [67]:
arr_final = np.concatenate([array1, array2])

In [68]:
arr_final

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[9,10],[11,12]])

In [73]:
arr_final = np.concatenate((array1,array2), axis=1)

In [74]:
arr_final

array([[ 1,  2,  9, 10],
       [ 3,  4, 11, 12]])

In [75]:
array1

array([[1, 2],
       [3, 4]])

In [76]:
np.where(array1%2 == 0)

(array([0, 1], dtype=int64), array([1, 1], dtype=int64))

In [77]:
array1[np.where(array1 == 4)]

array([4])

In [78]:
array1

array([[1, 2],
       [3, 4]])

In [79]:
array1 *2

array([[2, 4],
       [6, 8]])

In [82]:
# if one of your array is all 1s or 0s, you can broadcast this onto another array
np.array([1,1,8,1,9]) * np.array([[6,7,5,8,7],[8,9,4,5,2]])


array([[ 6,  7, 40,  8, 63],
       [ 8,  9, 32,  5, 18]])

In [83]:
x = np.random.randint(100)
x

57

In [86]:
#generate random float
x = np.random.rand()
x

0.06281217695810182

In [87]:
# generate a random array
x = np.random.randint(100, size=(5))
x

array([43, 15, 15, 85, 98])

In [88]:
# generate a random array
x = np.random.randint(100, size=(3,5))
x

array([[37, 10, 95, 46, 47],
       [87, 28, 42,  4, 42],
       [69, 62, 92, 83, 40]])

In [89]:
x = np.random.normal(loc=1, scale=2, size=(2,3))
x

array([[-1.43442941,  1.49570251,  3.44381158],
       [-1.04068037,  3.84424853,  2.76664478]])

In [90]:
x = np.random.uniform(size=(2,3))
x

array([[0.4696773 , 0.01145254, 0.79127204],
       [0.25166583, 0.3398633 , 0.24343821]])

In [5]:
import numpy as np

def first_last(arr):
    return arr.flat[0], arr.flat[-1]

# Testing the function on the provided arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 3, 4, 5], [1, 4, 5, 7]])
arr3 = np.array([[[1, 3, 4, 5], [1, 4, 5, 7]], [[6, 7, 8, 9], [7, 8, 7, 6]]])

In [6]:
first_last(arr1)

(1, 5)

In [7]:
first_last(arr2)

(1, 7)

In [8]:
first_last(arr3)

(1, 6)